### PR TITLE
Make it easier to modify settings from the sidebar

### PR DESCRIPTION
**Pull request by bartj3**
Modifying the settings is quite unfriendly to the user. It should be more similar to the way it's handled in the blogging engine.

### CODE REVIEW

**Comment by bartj3** [comment]
Work in progress, just the basic menu setup, no actual settings forms yet.
Do we want to include the api key in the settings or keep that in the config?

**Comment by johanb** [comment]
API Key goes into config file, it's not really something a user modifies.. at least that's my opinion

**Comment by johanb** [comment]
@Bartj3 are you working on this right now ? I can have a look if you want.

**Comment by bartj3** [comment]
Not working on it, had too many duvels :p
Planned to use the same lightbox form as used for the campaign send (and blog extension settings).
But wont have time to work on this for a week so have fun ;)

**Comment by johanb** [comment]
@Bartj3 ok, enjoy. I'll dive into it tomorrow.

**Comment by bartj3** [comment]
Internet has quite some issues here so can't google for a solution but there's a 404 issue as mentioned in the commit message.

**Pull request closed without merging**
